### ISSUE TITLE
what should i enter in first page?

### ISSUE THREAD

**Issue by rsa408** [Southpaw-TACTIC/Team#1]
hi 
I am installing team 4.3 and when i run it it asks for name and password. 
what ever I try are wrong. what should I use?
i even tried the reset password however it has a wrong folder address( instead of 4.3 pointing to 4.1)

START "Reset Password" /B ".\python\python.exe" ".\tactic-4.1\src\bin\util\reset_admin_password.py"

but in the page it shows the following error:

C:\Program Files\TACTIC 4.3>START "Reset Password" /B ".\python\python.exe" ".\t
actic-4.3\src\bin\util\reset_admin_password.py"

C:\Program Files\TACTIC 4.3>WARNING: no expiry on ticket for Sqlite and MySQL
Traceback (most recent call last):
  File ".\tactic-4.3\src\bin\util\reset_admin_password.py", line 28, in <module>

```
admin.set_value("password", password)
```

AttributeError: 'NoneType' object has no attribute 'set_value'

**Comment by rsa408** [comment]
thanks for your appreciation.  unfortunately still i have a problem after changing you mentiond file still it shows the following problem:

C:\Program Files\TACTIC>START "Reset Password" /B ".\python\python.exe" ".\tactic-4.3\src\bin\util\reset_admin_password.py"

C:\Program Files\TACTIC>  File ".\tactic-4.3\src\bin\util\reset_admin_password.py", line 25
    search.set_show_retired(True)
         ^
IndentationError: expected an indented block 

also once again i completely removed and installed a fresh tactic team and in opening it shows me the name and password following photo:
![tactic](https://cloud.githubusercontent.com/assets/4402631/5597454/b15b0086-92b7-11e4-868b-70766ce3dca3.png)

i don't know how can i solve it. when i use my tactic username and password the following appears:
![tactic2](https://cloud.githubusercontent.com/assets/4402631/5597508/9a340fc8-92b8-11e4-9caf-ba1bed35fd30.png)


thanks

**Comment by oboreo** [comment]
The indentation screws up in copy and paste message, Here is the link to the updated file on github.. When you freshly install, it by default sees it as an upgrade unless you clean out the ProgramData/TACTIC  folder.. Anyways, here is the update file which will enable you to run the reset password file.  https://github.com/Southpaw-TACTIC/TACTIC/blob/4.3/src/bin/util/reset_admin_password.py
